// a = 1
// b = 2
// c = 3 ...

pub fn encode_char(chr: char) -> Option<u8> {
    match chr {
        'a' => Some(1),
        'b' => Some(2),
        'c' => Some(3),
        'd' => Some(4),
        'e' => Some(5),
        'f' => Some(6),
        'g' => Some(7),
        'h' => Some(8),
        'i' => Some(9),
        'j' => Some(10),
        'k' => Some(11),
        'l' => Some(12),
        'm' => Some(13),
        'n' => Some(14),
        'o' => Some(15),
        'p' => Some(16),
        'q' => Some(17),
        'r' => Some(18),
        's' => Some(19),
        't' => Some(20),
        'u' => Some(21),
        'v' => Some(22),
        'w' => Some(23),
        'x' => Some(24),
        'y' => Some(25),
        'z' => Some(26),
        '0' => Some(27),
        '1' => Some(28),
        '2' => Some(29),
        '3' => Some(30),
        '4' => Some(31),
        '5' => Some(32),
        '6' => Some(33),
        '7' => Some(34),
        '8' => Some(35),
        '9' => Some(36),
        _ => None,
    }
}

pub fn decode_char(encoded: u8) -> Option<char> {
    match encoded {
        1 => Some('a'),
        2 => Some('b'),
        3 => Some('c'),
        4 => Some('d'),
        5 => Some('e'),
        6 => Some('f'),
        7 => Some('g'),
        8 => Some('h'),
        9 => Some('i'),
        10 => Some('j'),
        11 => Some('k'),
        12 => Some('l'),
        13 => Some('m'),
        14 => Some('n'),
        15 => Some('o'),
        16 => Some('p'),
        17 => Some('q'),
        18 => Some('r'),
        19 => Some('s'),
        20 => Some('t'),
        21 => Some('u'),
        22 => Some('v'),
        23 => Some('w'),
        24 => Some('x'),
        25 => Some('y'),
        26 => Some('z'),
        27 => Some('0'),
        28 => Some('1'),
        29 => Some('2'),
        30 => Some('3'),
        31 => Some('4'),
        32 => Some('5'),
        33 => Some('6'),
        34 => Some('7'),
        35 => Some('8'),
        36 => Some('9'),
        _ => None,
    }
}